version: "3"

services:
  
  pablex_api:
    image: pablex/pablex_api
    container_name: pablex_api
    restart: always
    ports:
      - "8082:8082"
    networks:
      - pablex_network
    healthcheck:
      test: "curl --fail --silent localhost:8082/health/ | grep true || exit 1"
      interval: 20s
      timeout: 5s
      retries: 10
      start_period: 40s
    environment:
      DATABASE_HOST: "pablex_mysql"
      DATABASE_DB: "pablex_db"
      DATABASE_USER: "${DATABASE_USER}"
      DATABASE_USER_PASSWORD: "${DATABASE_USER_PASSWORD}"
    depends_on:
      pablex_mysql:
        condition: service_healthy

  pablex_mysql:
    image: mysql
    container_name: pablex_mysql
    restart: always
    volumes:
      - pablex_mysql_conf:/etc/mysql/conf.d
      - pablex_mysql_data:/var/lib/mysql
      - "./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    networks:
      - pablex_network
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
      MYSQL_DATABASE: 'pablex_db'
      MYSQL_USER: "${DATABASE_USER}"
      MYSQL_PASSWORD: "${DATABASE_USER_PASSWORD}"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppass"]
      interval: 20s
      timeout: 5s
      retries: 10
      start_period: 40s

networks:
  pablex_network:
    name: pablex_network

volumes:
  pablex_mysql_conf:
    name: pablex_mysql_conf
  pablex_mysql_data:
    name: pablex_mysql_data