INSERT INTO CONSUMERS (CONSUMERS_FIRSTNAME, CONSUMERS_LASTNAME, CONSUMERS_CHECK, CONSUMERS_KEY)
  VALUES ('TOTO','TOTO',FALSE,'TOTO');
INSERT INTO CONSUMERS (CONSUMERS_FIRSTNAME, CONSUMERS_LASTNAME, CONSUMERS_CHECK, CONSUMERS_KEY)
  VALUES ('TATA','TATA',FALSE,'TATA');