CREATE TABLE CONSUMERS (
    CONSUMERS_ID INT PRIMARY KEY AUTO_INCREMENT,
    CONSUMERS_FIRSTNAME VARCHAR(50) NOT NULL,
    CONSUMERS_LASTNAME VARCHAR(50) NOT NULL,
    CONSUMERS_CHECK BOOLEAN NOT NULL,
    CONSUMERS_KEY VARCHAR(50) UNIQUE NOT NULL
); 